disabled_rules:
  - todo
  - trailing_comma
  - nesting

type_name:
  excluded:
    - ID

identifier_name:
  allowed_symbols: ["$", "_"]
  excluded:
    - id

excluded:           # Paths SwiftLint should ignore
  - DerivedData
  - .build

opt_in_rules:
  - attributes
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - missing_docs
  - modifier_order
  - convenience_type
  - pattern_matching_keywords
  - multiline_parameters_brackets
  - multiline_arguments_brackets

custom_rules:
  spaces_over_tabs:
    included: ".*\\.swift"
    name: "Spaces over Tabs"
    regex: "\t"
    message: "Prefer spaces for indents over tabs. See Xcode setting: 'Text Editing' -> 'Indentation'"
    severity: warning
